common-params:
  &publish-android-artifacts-docker-container
  docker#v3.8.0:
    image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
    propagate-environment: true
    environment:
      # DO NOT MANUALLY SET THESE VALUES!
      # They are passed from the Buildkite agent to the Docker container
      - "AWS_ACCESS_KEY"
      - "AWS_SECRET_KEY"

steps:
  - label: "Publish :mp4compose"
    key: "publish-mp4compose"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-mp4compose.sh

  - label: "Publish :photoeditor"
    key: "publish-photoeditor"
    depends_on:
      - "publish-mp4compose"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-photoeditor.sh

  - label: "Publish :stories"
    key: "publish-stories"
    depends_on:
      - "publish-photoeditor"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-stories.sh
