common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

steps:
  - label: "Publish :mp4compose"
    key: "publish-mp4compose"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-mp4compose.sh

  - label: "Publish :photoeditor"
    key: "publish-photoeditor"
    depends_on:
      - "publish-mp4compose"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-photoeditor.sh

  - label: "Publish :stories"
    key: "publish-stories"
    depends_on:
      - "publish-photoeditor"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-stories.sh
