common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "checkstyle"
    key: "checkstyle"
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew checkstyle
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/checkstyle/checkstyle.*"

  - label: "ktlint"
    key: "ktlint"
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew ciktlint
    plugins: *common_plugins
    artifact_paths:
      - "**/build/ktlint.xml"

  - label: "Publish :mp4compose"
    key: "publish-mp4compose"
    depends_on:
      - "checkstyle"
      - "ktlint"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-mp4compose.sh

  - label: "Publish :photoeditor"
    key: "publish-photoeditor"
    depends_on:
      - "publish-mp4compose"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-photoeditor.sh

  - label: "Publish :stories"
    key: "publish-stories"
    depends_on:
      - "publish-photoeditor"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/publish-stories.sh
